# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20160502_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
