# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='conf_name',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
